//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using NSubstitute;
using System;
using AssemblyCSharp;
using AssemblyCSharp.Utils;
namespace Tests
{
	[TestFixture()]
	public class ModelsTest{
		[Test()]
		public void TestCreate (){

		}
	}
}

