//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Net.Sockets;
namespace AssemblyCSharp
{
	public class ClientData {
		public TcpClient Client = null;
		public byte[] data = new Byte[1024];
		public String message = "";
		public ClientData(){}
		public ClientData(TcpClient client){
			this.Client = client;
		}
	}
}

