//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp.Utils
{
	public struct StoredAction {
		public string method;
		public string args;
		public float duration;
		public ClientData client;

		/* Constructors
		 * TODO : make this list shorter !
		 */
		public StoredAction(string method){
			this.method = method.ToLower();
			this.args = null;
			this.duration = 0;
			this.client = null;
		}
		public StoredAction(string method,ClientData client){
			this.method = method.ToLower();
			this.args = null;
			this.duration = 0;
			this.client = client;
		}
		public StoredAction(string method,string args){
			this.method = method.ToLower();
			this.args = args;
			this.duration = 0;
			this.client = null;
		}
		public StoredAction(string method,string args,ClientData client){
			this.method = method.ToLower();
			this.args = args;
			this.duration = 0;
			this.client = client;
		}
		public StoredAction(string method,float length){
			this.method = method.ToLower();
			this.args = null;
			this.duration = length;
			this.client = null;
		}
		public StoredAction(string method,string args,float length){
			this.method = method.ToLower();
			this.args = args;
			this.duration = length;
			this.client = null;
		}
		public StoredAction(string method,string args,string length){
			this.method = method.ToLower();
			this.args = args;
			this.duration = float.Parse(length);
			this.client = null;
		}
		public StoredAction(string method,string args,string length,ClientData client){
			this.method = method.ToLower();
			this.args = args;
			this.duration = float.Parse(length);
			this.client = client;
		}
		
	}
}

