//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
		public class IdleParser {
			
			private Models models;
			public IdleParser (Models models){
				this.models = models;
				//pos = Input.mousePosition;
			}
			public bool update(){
				Model model = models.getCurrent();
				//Rotate until rotation = Quaternion.identity.
				Quaternion currentRotation = model.getRotation();
				
				return true;
			}
		}
}
	

