//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
	public class KeyParser:BaseParser {

		private Models models;
		public KeyParser (Models models){
			this.models = models;
			//pos = Input.mousePosition;
		}
		public override bool update() {
			Model model = models.getCurrent();
			bool ret = false;
			//Horizontal rotation
			if(Input.GetKey("q")){
				ret= true;
				model.setRotation(0,1,0);
			}else if(Input.GetKey("d")){
				ret= true;
				model.setRotation(0,-1,0);
			}
			//roll
			if(Input.GetKey("a")){
				ret= true;
				model.setRotation(0,0,1);
			}else if(Input.GetKey("e")){
				ret= true;
				model.setRotation(0,0,-1);
			}
			//vertical rotation
			if(Input.GetKey("z")){
				ret= true;
				model.setRotation(1,0,0);
			}else if(Input.GetKey("s")){
				ret= true;
				model.setRotation(-1,0,0);
			}else if(Input.GetKeyDown("r")){
				ret= true;
				models.next();
			}
			return ret;
		}
	}
}

