//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class LimitedQueue<T> : Queue<T>
	{
		private int limit = -1;
		
		public int Limit
		{
			get { return limit; }
			set { limit = value; }
		}
		
		public LimitedQueue(int limit)
			: base(limit)
		{
			this.Limit = limit;
		}
		
		public new void Enqueue(T item)
		{
			if (this.Count >= this.Limit)
			{
				this.Dequeue();
			}
			base.Enqueue(item);
		}
	}
}

