//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

namespace AssemblyCSharp
{
	public class Model{

		private GameObject obj;

		public Model (GameObject mesh){
			this.obj =  mesh;
			this.obj.SetActive(false);
		}

		public void setRotation(float x,float y, float z){
			this.setRotation(new Vector3(x,y,z));
		}
		public void setRotation(Vector3 rot){
			this.obj.transform.RotateAround(Vector3.zero,rot,100*Time.deltaTime);
			this.obj.transform.LookAt(Vector3.zero);
			//this.obj.transform.Rotate(rot*Time.deltaTime);
		}
		public void setActive(bool active){
			//MeshFilter mf = (MeshFilter) this.obj.GetComponent<MeshFilter>();
			//Debug.Log ( mf);
			this.obj.transform.rotation = Quaternion.identity;
			this.obj.SetActive (active);
		}
	}
}
