//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using LitJson;

namespace AssemblyCSharp
{
	public class Models{
		private List<Model> list;
		private JsonData config;
		private int index;
		public Models (GameObject def){
			index = 0;
			list = new List<Model>();
			string line;
			//Get configuration nodes using litJSON
			ConfNode[] config = JsonMapper.ToObject<ConfNode[]>(((TextAsset)Resources.Load("config", typeof(TextAsset))).text);

			UnityEngine.Object[] listObjects = Resources.LoadAll("Objects", typeof(GameObject));
			foreach (GameObject listObject in listObjects) {
				Model model;
				//Instantiate game object. Maybe we're just a step away to make this one visible, but I can't find it so just re create it...
				GameObject obj = (GameObject) GameObject.Instantiate (listObject, Vector3.zero, Quaternion.identity);

				ConfNode node = Array.Find(config,element=>obj.name.Equals(element.name+"(Clone)",StringComparison.OrdinalIgnoreCase));
				model = new Model(obj,node);
				model.setActive (false);
				list.Add (model);
			}
			if( list.Count == 0){
				Debug.Log ("no objects found. Please add objects to your Resources/Objects folder");
				list.Add (new Model((GameObject) GameObject.Instantiate (def, Vector3.zero, Quaternion.identity)));
			}
			this.setCurrent(0);
		}


		public Model getCurrent(){
			return list[index];
		}
		public void next(){
			this.list[index].setActive(false);
			this.setCurrent(index+1);
		}
		public void setCurrent(int value){

			if(value <list.Count && value >0){
				this.index = value;
			}else{
				this.index = 0;
			}
			this.list[index].setActive(true);
		}

	}
}
