//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Models{
		private List<Model> list;
		private int index;
		public Models (GameObject def){
			index = 0;
			list = new List<Model>();
			UnityEngine.Object[] listObjects = Resources.LoadAll ("Objects", typeof(GameObject));
			foreach (GameObject listObject in listObjects) {
				GameObject obj = (GameObject) GameObject.Instantiate (listObject, Vector3.zero, Quaternion.identity);
				//scale (obj,def.collider);
				Model model = new Model(obj);
				//model.scale(def.collider);
				//model.center();
				model.setActive (false);
				list.Add (model);
			}
			if( list.Count == 0){
				Debug.Log ("no objects found. Please add objects to your Resources/Objects folder");
				list.Add (new Model((GameObject) GameObject.Instantiate (def, Vector3.zero, Quaternion.identity)));
			}
			this.setCurrent(0);
		}


		public Model getCurrent(){
			return list[index];
		}
		public void next(){
			this.list[index].setActive(false);
			this.setCurrent(index+1);
		}
		public void setCurrent(int value){

			if(value <list.Count && value >0){
				this.index = value;
			}else{
				this.index = 0;
			}
			this.list[index].setActive(true);
		}

	}
}
