//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
	public interface  ISetup {
		void SetRight(GameObject camera);
		void SetLeft(GameObject camera);
		void SetFront(GameObject camera);
		void SetBack(GameObject camera);
	}
}

