//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
	public class SetupFocus :ISetup {
		GameObject master_cam;
		public SetupFocus (GameObject master_cam){
			this.master_cam = master_cam;
		}

		void ISetup.SetFront(GameObject camera){
			
		}
		void ISetup.SetLeft(GameObject camera){
			
		}
		void ISetup.SetRight(GameObject camera){
			
		}
		void ISetup.SetBack(GameObject camera){
			
		}
	}
}

