//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using LitJson;

namespace AssemblyCSharp.Configure
{
	public class ConfigReader{
		private string fileName;
		private ConfFile conf;

		public ConfNode[] Nodes {
			get{
				return conf.nodes;
			}
		}
		public Options Options {
			get{
				return this.conf.options;
			}
		}
		public ConfigReader (string fileName){
			this.fileName = fileName;
			this.getConfig ();
		}
		public ConfigReader (){
			this.fileName = "config";
			this.getConfig ();
		}
		public void getConfig(){
			TextAsset text = (TextAsset)Resources.Load (this.fileName, typeof(TextAsset));
			if(text != null && text.text != null){
				try{
					this.conf = JsonMapper.ToObject<ConfFile> (text.text);
				} catch(JsonException e){
					Debug.LogWarning(e.ToString());
					this.conf = new ConfFile();
				}
			}

		}

	}
}

