//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using System.Collections;
using System.Collections.Generic;
using LitJson;
using AssemblyCSharp.Utils;

namespace AssemblyCSharp.Configure
{
	public class ConfigReader{
		private string fileName;
		private ConfFile conf;
		private IConfFileLoader loader;
		public ConfNode[] Nodes {
			get{
				return conf.nodes;
			}
		}
		public Options Options {
			get{
				return this.conf.options;
			}
		}
		public ConfigReader (string fileName){
			this.fileName = fileName;
			this.loader = new FileLoader();
			this.getConfig ();
		}
		public ConfigReader (){
			this.fileName = "config";
			this.loader = new FileLoader();
			this.getConfig ();
		}
		public ConfigReader (string fileName,IConfFileLoader loader){
			this.fileName = fileName;
			this.loader = loader;
			this.getConfig ();
		}


		private void getConfig(){
			string text = this.loader.getConfig(this.fileName);
			if(text != null){
				try{
					this.conf = JsonMapper.ToObject<ConfFile> (text);
				} catch(JsonException e){
					this.conf = new ConfFile();
				}
			}else{
				this.conf = new ConfFile();
			}

		}

	}
}

