//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
namespace AssemblyCSharp
{
	namespace Configure {
		public class ConfNode{
			public string name	{ get; set; }
			public string[] objects;
			public float[] axes;


			public ConfNode (){
				defaults ();
			}
			public ConfNode (string name){
				defaults ();
				this.name=name;
			}
			private void defaults(){
				this.name="";
				this.axes = new float[3];
				this.axes[0]= 1f;
				this.axes[1] = 1f;
				this.axes[2] = 1f;
			}
			public Vector3 getAxes(){
				return new Vector3(this.axes[1],this.axes[0],this.axes[2]);
			}
		}
	}
}

