//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using NSubstitute;
using System;
using System.IO;
using System.Reflection;
using AssemblyCSharp.Configure;
using AssemblyCSharp.Utils;



namespace Tests.Configure
{


	[TestFixture("baseConf.json")]
	[TestFixture("invalidConf.json")]
	[TestFixture("invalidJson.json")]
	public class ConfigReaderTest{
		private string conf;
		public ConfigReaderTest(string conf){

			this.conf = conf;
		}

		[Test()]
		public void ReadConfig (){
			Assembly a = Assembly.GetExecutingAssembly();
			Stream s = a.GetManifestResourceStream("Tests.Configure.Fixtures."+conf);
			StreamReader sr = new StreamReader(s);
			string value = sr.ReadToEnd();
			sr.Close();
			var loader = Substitute.For<IConfFileLoader>();
			loader.getConfig(conf).Returns(value);
			ConfigReader reader = new ConfigReader(conf, loader);

			Assert.IsNotNull(reader);
			Assert.IsNotNull(reader.Options);

			Assert.IsInstanceOf<Options>( reader.Options );
			Assert.IsInstanceOf<ConfNode[]>( reader.Nodes );
		}
	}
}

